"""
OIO Racing - Photo Log Utilities

Shared library for reading and writing photo-log.md files in the OIO brain.

Photo metadata and workflow state are stored as markdown in the repo under:
  photos/{driver}/{vehicle-slug}/photo-log.md

Unidentified photos land in:
  photos/triage/photo-log.md

Actual photo binaries are stored in Supabase Storage (oio-photos bucket).

Entry format inside a photo-log.md file:

  ## IMG_1234.JPG
  - google_photos_id: ABC123
  - supabase_url: https://...
  - thumbnail_url: https://...
  - captured_at: 2026-04-01T12:00:00+00:00
  - source_description: Ian sliding through turn 3
  - rough_caption: Ian sliding through turn 3
  - vehicle_key: goblin
  - auto_identified_vehicle_key: goblin
  - identification_confidence: 0.92
  - workflow_status: caption_generated
  - final_caption: The Goblin doing what it does best at RayRocks.
  - postbridge_draft_id: pb_abc123
  - tentative_publish_at: 2026-04-08T16:00:00+00:00
  - posted_at: none
  - notes: Blue AW11 MR2 mid-slide on dirt, 2MR door graphics, dust trail.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).parent.parent
PHOTOS_ROOT = REPO_ROOT / "photos"
TRIAGE_LOG = PHOTOS_ROOT / "triage" / "photo-log.md"

# vehicle_key → (driver, folder-slug)
VEHICLE_FOLDERS: dict[str, tuple[str, str]] = {
    "goblin": ("ian", "mr2-goblin"),
    "dale": ("ian", "celica-dale"),
    "fittycent": ("ian", "fit-fittycent"),
    "nessie": ("ian", "cressida-nessie"),
    "killer-corolla": ("ian", "corolla-killer"),
    "geoffrey": ("ian", "dauphine-geoffrey"),
    "tootie": ("karen", "tootie"),
    "mgb-gt": ("ryan", "mgb-gt"),
    "ae86": ("ryan", "ae86"),
}


def log_path_for_vehicle(vehicle_key: Optional[str]) -> Path:
    """Return the photo-log.md path for a vehicle_key, or the triage log if unknown."""
    if vehicle_key and vehicle_key in VEHICLE_FOLDERS:
        driver, slug = VEHICLE_FOLDERS[vehicle_key]
        return PHOTOS_ROOT / driver / slug / "photo-log.md"
    return TRIAGE_LOG


def ensure_log_exists(log_path: Path, vehicle_key: Optional[str] = None) -> None:
    """Create a photo-log.md with frontmatter if it does not already exist."""
    if log_path.exists():
        return

    log_path.parent.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    if log_path == TRIAGE_LOG:
        title = "Triage — Photo Log"
        tags = "[photos, triage, unidentified]"
        summary = (
            "Photos ingested from Google Photos that could not be auto-identified. "
            "Assign vehicle_key and set workflow_status to metadata_complete when ready "
            "for caption generation."
        )
    elif vehicle_key and vehicle_key in VEHICLE_FOLDERS:
        driver, slug = VEHICLE_FOLDERS[vehicle_key]
        display = slug.replace("-", " ").title()
        title = f"{display} — Photo Log"
        tags = f"[photos, {vehicle_key}, {driver}]"
        summary = f"Photo log for {display}. Auto-generated by the photo ingestion workflow."
    else:
        title = "Photo Log"
        tags = "[photos]"
        summary = "Auto-generated photo log."

    frontmatter = f"""---
title: {title}
type: reference
status: active
owner: Ian Jennings
updated: {today}
tags: {tags}
source_of_truth: false
summary: {summary}
---

# {title}

> Photo entries are written by the ingestion workflow.
> To advance a triage photo: set `vehicle_key`, optionally update `rough_caption`, then change `workflow_status` to `metadata_complete`.

---
"""
    log_path.write_text(frontmatter)


def parse_entries(log_path: Path) -> dict[str, dict[str, str]]:
    """
    Parse a photo-log.md and return all photo entries keyed by google_photos_id.

    Each value dict contains all key-value fields plus '_filename' and '_log_path'.
    """
    if not log_path.exists():
        return {}

    text = log_path.read_text()
    entries: dict[str, dict[str, str]] = {}

    # Split on ## headings — capturing group keeps heading text
    parts = re.split(r"^## (.+)$", text, flags=re.MULTILINE)
    # parts[0] = frontmatter, then alternating [heading_text, body, heading_text, body, ...]

    i = 1
    while i + 1 < len(parts):
        filename = parts[i].strip()
        body = parts[i + 1]

        entry: dict[str, str] = {"_filename": filename, "_log_path": str(log_path)}
        for line in body.splitlines():
            m = re.match(r"^- ([\w_-]+): (.*)$", line)
            if m:
                entry[m.group(1).strip()] = m.group(2).strip()

        gp_id = entry.get("google_photos_id")
        if gp_id:
            entries[gp_id] = entry
        i += 2

    return entries


def all_entries() -> dict[str, dict[str, str]]:
    """Return every photo entry from every photo-log.md in the photos/ tree, keyed by google_photos_id."""
    result: dict[str, dict[str, str]] = {}
    for log_file in PHOTOS_ROOT.rglob("photo-log.md"):
        result.update(parse_entries(log_file))
    return result


def append_entry(log_path: Path, entry: dict[str, str]) -> None:
    """Append a new photo entry block to a photo-log.md file."""
    ensure_log_exists(log_path, entry.get("vehicle_key"))

    filename = entry.get("_filename") or entry.get("google_photos_id", "unknown")

    lines = [f"\n## {filename}"]
    for key, value in entry.items():
        if key.startswith("_"):
            continue
        val = value if value is not None else "none"
        lines.append(f"- {key}: {val}")
    lines.append("")  # blank line after entry

    with log_path.open("a") as f:
        f.write("\n".join(lines) + "\n")

    _touch_updated(log_path)


def update_entry(log_path: Path, google_photos_id: str, updates: dict[str, str]) -> bool:
    """
    Update fields in an existing entry inside a photo-log.md.

    Returns True if found and updated, False if google_photos_id was not found.
    """
    if not log_path.exists():
        return False

    text = log_path.read_text()

    # Split preserving headings
    parts = re.split(r"^(## .+)$", text, flags=re.MULTILINE)
    # parts[0] = preamble; then alternating ['## heading', body, ...]

    found = False
    result = [parts[0]]

    i = 1
    while i + 1 < len(parts):
        heading = parts[i]
        body = parts[i + 1]
        result.append(heading)

        if f"google_photos_id: {google_photos_id}" in body:
            found = True
            updated_keys: set[str] = set()
            new_lines = []
            for line in body.splitlines():
                m = re.match(r"^- ([\w_-]+): (.*)$", line)
                if m:
                    key = m.group(1).strip()
                    if key in updates:
                        new_lines.append(f"- {key}: {updates[key]}")
                        updated_keys.add(key)
                    else:
                        new_lines.append(line)
                else:
                    new_lines.append(line)

            # Append any new keys not already present
            for key, value in updates.items():
                if key not in updated_keys:
                    new_lines.append(f"- {key}: {value}")

            result.append("\n".join(new_lines))
        else:
            result.append(body)

        i += 2

    if not found:
        return False

    log_path.write_text("".join(result))
    _touch_updated(log_path)
    return True


def entries_by_status(*statuses: str) -> list[dict[str, str]]:
    """Return all photo entries whose workflow_status is in the given list."""
    return [
        entry
        for entry in all_entries().values()
        if entry.get("workflow_status") in statuses
    ]


def _touch_updated(log_path: Path) -> None:
    """Update the 'updated:' date in the frontmatter of a log file."""
    if not log_path.exists():
        return
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    text = log_path.read_text()
    new_text = re.sub(
        r"^updated: \d{4}-\d{2}-\d{2}",
        f"updated: {today}",
        text,
        count=1,
        flags=re.MULTILINE,
    )
    log_path.write_text(new_text)
